#  애플리케이션 이름 설정
spring.application.name=minilog-jwt-with-auth

# 스프링 부트가 DB에 접근할 수 있도록 URL 설정
spring.datasource.url=jdbc:postgresql://localhost:5432/minilog
# 사용자 이름 및 비밀번호 설정
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# JDBC 드라이버를 사용해 DB에 접근하도록 설정( postgresql 기준 )
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate가 데이터베이스 스키마를 자동으로 업데이트하도록 설정
# 개발 중 테이블 및 컬럼 구조가 자동으로 업데이트
spring.jpa.hibernate.ddl-auto=update

# SQL 쿼리 출력 설정
spring.jpa.show-sql=true

# JWT Secret Key : openssl rand -base64 32
jwt.secret=${JWT_SECRET_KEY}